# source "http://rubygems.org"
# only needed for debugging the gem
# 	gem "rails", "2.3.8"
# 	gem "riot"
# 	gem "sqlite3"
# 	gem "ruby-debug"
# 	gem "awesome_print"
# 	gem "jeweler"
# 	gem "i18n"
# 	gem "multi_json"
